events {}

http {
    # Desafio Extra: Redirecionamento permanente (301) de HTTP para HTTPS 
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl; # Escutar Porta SSL
        server_name localhost;

        # Caminhos dos certificados no container
        ssl_certificate /etc/nginx/ssl/nginx-selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx-selfsigned.key;
        
        # Protocolos Recomendados 
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            root /usr/share/nginx/html; # Raiz do HTML 
            index index.html;
        }
    }
}